# permissions for end users to edit kboes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kbo-editor-role
rules:
- apiGroups:
  - apps.operator.kb.cx
  resources:
  - kboes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.operator.kb.cx
  resources:
  - kboes/status
  verbs:
  - get
