---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps.xca.k8s.kb.cx
  resources:
  - xcas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.xca.k8s.kb.cx
  resources:
  - xcas/finalizers
  verbs:
  - update
- apiGroups:
  - apps.xca.k8s.kb.cx
  resources:
  - xcas/status
  verbs:
  - get
  - patch
  - update
