# permissions for end users to edit xcas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: xca-editor-role
rules:
- apiGroups:
  - apps.xca.k8s.kb.cx
  resources:
  - xcas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.xca.k8s.kb.cx
  resources:
  - xcas/status
  verbs:
  - get
