# permissions for end users to view xcas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: xca-viewer-role
rules:
- apiGroups:
  - apps.xca.k8s.kb.cx
  resources:
  - xcas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.xca.k8s.kb.cx
  resources:
  - xcas/status
  verbs:
  - get
