# permissions for end users to view xtls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: xtls-viewer-role
rules:
- apiGroups:
  - xca.kb.cx
  resources:
  - xtls
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - xca.kb.cx
  resources:
  - xtls/status
  verbs:
  - get
